version: 2

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/clojure:lein-2.8.1
    environment:
      QT_QPA_PLATFORM: offscreen
    steps:
      - run: sudo apt-get update && sudo apt-get install -y rhino phantomjs
      - checkout
      - restore_cache:
          keys:
            - v1-{{ checksum "project.clj" }}
            - v1-
      - run: lein deps
      - run: lein check
      - run: lein test
      - run: lein doo rhino test once
      - save_cache:
          key: v1-{{ checksum "project.clj" }}
          paths:
            - ~/.m2
