version: 2

jobs:
  build:
    working_directory: ~/alphabase
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
      QT_QPA_PLATFORM: offscreen
    steps:
      - run: sudo apt-get update && sudo apt-get install -y phantomjs
      - checkout
      - restore_cache:
          keys:
            - alphabase-{{ checksum "project.clj" }}
            - alphabase-
      - run: lein deps
      - save_cache:
          key: alphabase-{{ checksum "project.clj" }}
          paths:
            - ~/.m2
      - run: lein check
      - run: lein test
      - run: lein doo phantom test once
