version: 2

jobs:
  build:
    working_directory: ~/alphabase
    docker:
      - image: circleci/clojure:lein-2.7.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - alphabase-{{ checksum "project.clj" }}
            - alphabase-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
      - run: lein check
      - run: lein test
      - run: lein doo phantom test once
